name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-typecheck:
    name: Lint, Test, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: yarn lint

      - name: Run Jest tests
        run: yarn test --ci --passWithNoTests

      - name: Run TypeScript type check
        run: yarn tsc --noEmit
